name: Daily Tweet Digest

on:
  schedule:  # 每日 08:00 (UTC+8)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 拉代码
    - uses: actions/checkout@v4

    # 2️⃣ Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3️⃣ 安装依赖
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install snscrape[twitter] markdownify openai

    # 4️⃣ 生成摘要
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python fetch_and_summarize.py

    # 5️⃣ 提交结果
    - name: Commit & push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name  "github-action-bot"
        git add -A docs/daily
        git commit -m "chore: refresh digest $(date -u '+%Y-%m-%d %H:%M')" || echo "no changes"
        git push
