name: Daily Tweet Digest

on:
  schedule:
    - cron:  '0 0 * * *'          # 每日 08:00 (UTC+8)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install feedparser markdownify openai

    - name: Generate digest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python fetch_and_summarize.py

    - name: Commit & push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name  "github-action-bot"
        git add -A docs/daily
        git commit -m "chore: refresh digest $(date -u '+%Y-%m-%d %H:%M')" || echo "nothing to commit"
        git push
