name: Daily Tweet Digest            # 工作流名称，可自行修改

# ─────────────────────────────── 触发条件 ───────────────────────────────
on:
  schedule:                         # 每日 08:00 (UTC+8) 运行；GitHub Actions 使用 UTC
    - cron:  '0 0 * * *'            # 00:00 UTC = 08:00 CST/台北
  workflow_dispatch:                # 允许在 Actions 页面手动触发

# ─────────────────────────────── 权限 ───────────────────────────────
# 需要推送回 main 分支，因此授予写权限
permissions:
  contents: write

# ─────────────────────────────── 作业定义 ───────────────────────────────
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ 安装 Python 3.11
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3️⃣ 安装依赖（包括最新版 snscrape）
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install --no-cache-dir git+https://github.com/JustAnotherArchivist/snscrape.git

    # 4️⃣ 运行抓取 + 摘要脚本
    - name: Fetch tweets & generate digest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # 请在仓库 Secrets 中设置
      run: python fetch_and_summarize.py

    # 5️⃣ 提交生成的 Markdown（始终 add -A 覆盖）
    - name: Commit & push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name  "github-action-bot"
        git add -A docs/daily
        git commit -m "chore: refresh digest $(date -u '+%Y-%m-%d %H:%M')" || echo "nothing to commit"
        git push

    # ───────── 如果你启用了邮件推送，可在此处追加发送步骤 ─────────
    # - name: Send email
    #   env:
    #     SGKEY: ${{ secrets.SENDGRID_API_KEY }}
    #     TO:    ${{ secrets.EMAIL_TO }}
    #   run: <curl 调 SendGrid 的脚本，略>
